from __future__ import annotations

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from ..config import GENERATED_DIR
from ..services import history as chat_db

router = APIRouter()


@router.get("/api/chat/{chat_id}/chart")
def latest_chart(chat_id: str) -> FileResponse:
    """Serve the newest chart referenced by a persisted assistant message."""
    chat = chat_db.get_chat(chat_id)
    if chat is None:
        raise HTTPException(status_code=404, detail="Chat not found")
    # Search newest-first so a chat with multiple analyses displays its latest chart.
    for message in reversed(chat.get("messages", [])):
        if message.get("role") == "assistant" and message.get("chart"):
            name = message["chart"].rsplit("/", 1)[-1]
            # The filename is generated by the server; only resolve it inside the
            # generated directory and never accept an arbitrary filesystem path.
            path = GENERATED_DIR / name
            if path.exists():
                return FileResponse(path, media_type="image/png")
            break
    raise HTTPException(status_code=404, detail="No chart found for this chat")